on:
  push:
    branches:
      - "main"
jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: "https://registry.npmjs.org"
      - name: Install npm packages
        run: |
          yarn install
      - name: Can Publish
        working-directory: ./packages/lib
        run: yarn can-npm-publish --verbose
      - name: typecheck
        run: yarn run typecheck
      - name: lint
        run: yarn run lint
      - name: format
        run: yarn run format
      - name: build
        run: yarn run lib run build:prd
